import type { Recommendation } from '@oss-preflight/core';
import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

export interface ScaffoldResult {
  success: boolean;
  skipped: boolean;
  message: string;
}

/**
 * Generate a version hash for idempotency check
 */
function generateVersionHash(recommendation: Recommendation): string {
  const hashInput = `${recommendation.candidate.name}@${recommendation.candidate.version}`;
  return crypto.createHash('sha256').update(hashInput).digest('hex').substring(0, 16);
}

/**
 * Check if scaffold already exists with matching version hash
 */
function checkIdempotency(outputDir: string, versionHash: string): boolean {
  const hashFile = path.join(outputDir, '.scaffold-version');
  
  if (!fs.existsSync(outputDir)) {
    return false;
  }

  if (!fs.existsSync(hashFile)) {
    return false;
  }

  const existingHash = fs.readFileSync(hashFile, 'utf-8').trim();
  return existingHash === versionHash;
}

/**
 * Interpolate template variables
 */
function interpolateTemplate(content: string, recommendation: Recommendation): string {
  return content
    .replace(/\{\{PACKAGE_NAME\}\}/g, recommendation.candidate.name)
    .replace(/\{\{PACKAGE_VERSION\}\}/g, recommendation.candidate.version)
    .replace(/\{\{REPOSITORY_URL\}\}/g, recommendation.candidate.repositoryUrl || '')
    .replace(/\{\{HOMEPAGE_URL\}\}/g, recommendation.candidate.homepageUrl || '');
}

/**
 * Copy template directory to output directory with variable interpolation
 */
function copyTemplate(templateDir: string, outputDir: string, recommendation: Recommendation): void {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const entries = fs.readdirSync(templateDir, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(templateDir, entry.name);
    const destPath = path.join(outputDir, entry.name);

    if (entry.isDirectory()) {
      copyTemplate(srcPath, destPath, recommendation);
    } else {
      const content = fs.readFileSync(srcPath, 'utf-8');
      const interpolated = interpolateTemplate(content, recommendation);
      fs.writeFileSync(destPath, interpolated, 'utf-8');
    }
  }
}

/**
 * Generate README.md
 */
function generateReadme(recommendation: Recommendation): string {
  return `# Discord Summary Bot

A Discord bot that summarizes channel activity, built with ${recommendation.candidate.name}.

## Installation

\`\`\`bash
npm install
\`\`\`

## Configuration

Create a \`.env\` file with your Discord bot token:

\`\`\`
DISCORD_TOKEN=your_token_here
\`\`\`

## Running

\`\`\`bash
npm start
\`\`\`

## Testing

Run the smoke test (uses mocked messages, no credentials required):

\`\`\`bash
npm test
\`\`\`

## Package Information

- **Package**: ${recommendation.candidate.name}@${recommendation.candidate.version}
- **Repository**: ${recommendation.candidate.repositoryUrl || 'N/A'}
- **License**: ${recommendation.passport.facts.license?.value || 'Unknown'}

## Next Steps

1. Get a Discord bot token from https://discord.com/developers/applications
2. Add the token to your \`.env\` file
3. Invite the bot to your server
4. Run \`npm start\` to start the bot

## Generated by OSS Preflight

This scaffold was generated by OSS Preflight based on your project requirements.
`;
}

/**
 * Generate ADOPTION_REPORT.md
 */
function generateAdoptionReport(recommendation: Recommendation, smokeResult?: { pass: boolean; output: string; duration: number }): string {
  const timestamp = new Date().toISOString();
  
  let report = `# Adoption Report

**Generated**: ${timestamp}

## Selected Package

- **Name**: ${recommendation.candidate.name}
- **Version**: ${recommendation.candidate.version}
- **Ecosystem**: ${recommendation.candidate.ecosystem}
- **Score**: ${recommendation.score}/100

## Evidence Sources

`;

  // Add source URLs from facts
  const facts = recommendation.passport.facts;
  const sources = new Set<string>();

  if (facts.license?.source) sources.add(facts.license.source);
  if (facts.weeklyDownloads?.source) sources.add(facts.weeklyDownloads.source);
  if (facts.lastCommit?.source) sources.add(facts.lastCommit.source);
  if (facts.stars?.source) sources.add(facts.stars.source);
  if (facts.openIssues?.source) sources.add(facts.openIssues.source);

  for (const source of sources) {
    report += `- ${source}\n`;
  }

  report += `\n## Package Details

- **Repository**: ${recommendation.candidate.repositoryUrl || 'N/A'}
- **Homepage**: ${recommendation.candidate.homepageUrl || 'N/A'}
- **License**: ${facts.license?.value || 'Unknown'}
- **Weekly Downloads**: ${facts.weeklyDownloads?.value || 'N/A'}
- **Stars**: ${facts.stars?.value || 'N/A'}
- **Last Commit**: ${facts.lastCommit?.value || 'N/A'}

## Smoke Test

`;

  if (smokeResult) {
    if (smokeResult.pass) {
      report += `**Status**: PASS ✓\n`;
      report += `**Duration**: ${smokeResult.duration}ms\n\n`;
      report += `The smoke test completed successfully. The generated scaffold is ready to use.\n`;
    } else {
      report += `**Status**: FAIL ✗\n`;
      report += `**Duration**: ${smokeResult.duration}ms\n\n`;
      report += `### Error Output\n\n\`\`\`\n${smokeResult.output}\n\`\`\`\n`;
    }
  } else {
    report += `**Status**: Not run yet\n\n`;
    report += `Run \`npm test\` to execute the smoke test.\n`;
  }

  report += `\n## Next Steps

1. Review the generated code in \`src/\`
2. Run \`npm test\` to verify the smoke test passes
3. Configure your Discord bot token in \`.env\`
4. Customize the bot logic in \`src/index.ts\`
5. Deploy to your preferred hosting platform

## Tradeoffs

`;

  for (const tradeoff of recommendation.passport.interpretation.tradeoffs) {
    report += `- ${tradeoff}\n`;
  }

  if (recommendation.passport.interpretation.warnings.length > 0) {
    report += `\n## Warnings\n\n`;
    for (const warning of recommendation.passport.interpretation.warnings) {
      report += `- ${warning}\n`;
    }
  }

  report += `\n---\n\n*Generated by OSS Preflight*\n`;

  return report;
}

/**
 * Generate scaffold from recommendation
 */
export async function generateScaffold(
  recommendation: Recommendation,
  outputDir: string,
  smokeResult?: { pass: boolean; output: string; duration: number }
): Promise<ScaffoldResult> {
  try {
    const versionHash = generateVersionHash(recommendation);

    // Check idempotency - skip only if no smoke result provided
    if (!smokeResult && checkIdempotency(outputDir, versionHash)) {
      return {
        success: true,
        skipped: true,
        message: 'Scaffold already exists with matching version',
      };
    }

    // If smokeResult provided, only update adoption report
    if (smokeResult && checkIdempotency(outputDir, versionHash)) {
      const adoptionReport = generateAdoptionReport(recommendation, smokeResult);
      fs.writeFileSync(path.join(outputDir, 'ADOPTION_REPORT.md'), adoptionReport, 'utf-8');
      return {
        success: true,
        skipped: false,
        message: 'Adoption report updated with smoke test results',
      };
    }

    // Get template directory - resolve relative to this file
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = dirname(__filename);
    const templateDir = path.join(__dirname, '../templates/discord-summary-bot');

    if (!fs.existsSync(templateDir)) {
      throw new Error(`Template directory not found: ${templateDir}`);
    }

    // Create output directory
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Copy template files with interpolation
    copyTemplate(templateDir, outputDir, recommendation);

    // Generate README
    const readme = generateReadme(recommendation);
    fs.writeFileSync(path.join(outputDir, 'README.md'), readme, 'utf-8');

    // Generate adoption report
    const adoptionReport = generateAdoptionReport(recommendation, smokeResult);
    fs.writeFileSync(path.join(outputDir, 'ADOPTION_REPORT.md'), adoptionReport, 'utf-8');

    // Write version hash for idempotency
    fs.writeFileSync(path.join(outputDir, '.scaffold-version'), versionHash, 'utf-8');

    return {
      success: true,
      skipped: false,
      message: 'Scaffold generated successfully',
    };
  } catch (error) {
    return {
      success: false,
      skipped: false,
      message: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

// Made with Bob