/**
 * Run Command - P9 Phase 2
 *
 * Complete workflow: recommend, scaffold/adoption pack, verify, report.
 */

import { runRecommendPipeline, type RecommendPipelineOptions } from './recommend-command.js';
import { generateScaffold, runSmokeTest } from '@oss-preflight/scaffold';
import { createWorkflowTrace, type WorkflowTrace } from '@oss-preflight/core';
import type { Recommendation } from '@oss-preflight/core';
import * as fs from 'fs';
import * as path from 'path';

export interface RunOptions extends RecommendPipelineOptions {
  idea: string;
  out?: string;
  rank?: string;
}

type ArtifactKind = 'scaffold' | 'adoption-pack';

function generateReport(
  idea: string,
  recommendation: Recommendation,
  smokeTestPassed: boolean | null,
  smokeDuration: number | null,
  artifactPath: string,
  artifactKind: ArtifactKind
): string {
  const actionLabel = artifactKind === 'scaffold' ? 'Scaffold' : 'Adoption Pack';
  const smokeStatus =
    smokeTestPassed === null
      ? 'NOT RUN - no scaffold template was available for this recommendation'
      : smokeTestPassed
        ? 'PASSED'
        : 'FAILED';

  return `# OSS Preflight Run Report

## Input
**Idea:** ${idea}

## Selected Recommendation
**Package:** ${recommendation.candidate.name}@${recommendation.candidate.version}
**Rank:** ${recommendation.rank}
**Score:** ${recommendation.score.toFixed(2)}

### Evidence Passport
- **License:** ${recommendation.passport.facts.license?.value || 'Not available'}
- **Weekly Downloads:** ${recommendation.passport.facts.weeklyDownloads?.value || 'Not available'}
- **Stars:** ${recommendation.passport.facts.stars?.value || 'Not available'}
- **OpenSSF Score:** ${recommendation.passport.facts.openssfScore?.value || 'Not available'}

### Assessment
**Goal Fit:** ${recommendation.passport.interpretation.goalFit}

**Compatibility:** ${recommendation.passport.interpretation.compatibility}

${recommendation.passport.interpretation.tradeoffs.length > 0 ? `**Tradeoffs:**
${recommendation.passport.interpretation.tradeoffs.map((t) => `- ${t}`).join('\n')}` : ''}

${recommendation.passport.interpretation.warnings.length > 0 ? `**Warnings:**
${recommendation.passport.interpretation.warnings.map((w) => `- ${w}`).join('\n')}` : ''}

## ${actionLabel}
**Output Path:** ${artifactPath}
**Template:** ${recommendation.templateId || 'not available'}

## Smoke Test
**Status:** ${smokeStatus}
**Duration:** ${smokeDuration === null ? 'N/A' : `${smokeDuration}ms`}

## Next Steps
${artifactKind === 'scaffold' && smokeTestPassed ? `
1. Review the generated code in \`${artifactPath}\`
2. Install dependencies: \`cd ${artifactPath} && npm install\`
3. Review ADOPTION_REPORT.md for integration guidance
4. Customize the code for your specific use case
` : artifactKind === 'adoption-pack' ? `
1. Review \`${artifactPath}\`
2. Install the selected package in your project using your package manager
3. Review the evidence gaps before adopting the dependency
4. Add project-specific tests before merging
` : `
1. Review the smoke test errors
2. Check the generated code in \`${artifactPath}\`
3. Verify dependencies are correctly specified
4. Report issues if the scaffold template needs fixes
`}

---
*Generated by OSS Preflight*
`;
}

function generateAdoptionPack(idea: string, recommendation: Recommendation): string {
  const facts = recommendation.passport.facts;
  const sources = new Set<string>();

  for (const fact of Object.values(facts)) {
    if (fact?.source) {
      sources.add(fact.source);
    }
  }

  return `# OSS Preflight Adoption Pack

## Input
${idea}

## Selected Package
- Name: ${recommendation.candidate.name}
- Version: ${recommendation.candidate.version}
- Ecosystem: ${recommendation.candidate.ecosystem}
- Rank: ${recommendation.rank}
- Score: ${recommendation.score}

## Why This Was Recommended
${recommendation.passport.interpretation.goalFit}

${recommendation.passport.interpretation.compatibility}

## Evidence
- License: ${facts.license?.value ?? 'Not available'}
- Weekly downloads: ${facts.weeklyDownloads?.value ?? 'Not available'}
- Stars: ${facts.stars?.value ?? 'Not available'}
- Last commit: ${facts.lastCommit?.value ?? 'Not available'}
- OpenSSF score: ${facts.openssfScore?.value ?? 'Not available'}

## Evidence Sources
${sources.size > 0 ? [...sources].map((source) => `- ${source}`).join('\n') : '- No source URLs were available for collected facts'}

## Evidence Gaps
${Object.entries(facts)
  .filter(([, fact]) => fact === null)
  .map(([name]) => `- ${name}: not available`)
  .join('\n') || '- None'}

## Suggested Adoption Steps
1. Add the package with your package manager.
2. Read the linked upstream documentation and license.
3. Create a minimal integration test around the first use case.
4. Run your normal dependency audit before merging.

## Notes
No scaffold template was available for this package, so OSS Preflight generated this adoption pack instead of code.
`;
}

function writeWorkflowAndReport(
  outputDir: string,
  workflow: WorkflowTrace,
  idea: string,
  recommendation: Recommendation,
  smokeTestPassed: boolean | null,
  smokeDuration: number | null,
  artifactPath: string,
  artifactKind: ArtifactKind
): { workflowPath: string; reportPath: string } {
  fs.mkdirSync(outputDir, { recursive: true });

  const workflowPath = path.join(outputDir, 'workflow.json');
  fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2), 'utf-8');

  const reportPath = path.join(outputDir, 'REPORT.md');
  fs.writeFileSync(
    reportPath,
    generateReport(idea, recommendation, smokeTestPassed, smokeDuration, artifactPath, artifactKind),
    'utf-8'
  );

  return { workflowPath, reportPath };
}

/**
 * Run command handler - complete workflow.
 */
export async function runCommand(options: RunOptions): Promise<void> {
  try {
    if (!options.idea || options.idea.trim().length === 0) {
      console.error('Error: --idea is required');
      console.error('Usage: oss-preflight run --idea <string> [--out <directory>] [--rank <number>]');
      process.exit(2);
    }

    const requestedRank = options.rank ? parseInt(options.rank, 10) : null;
    if (requestedRank !== null && (isNaN(requestedRank) || requestedRank < 1 || requestedRank > 3)) {
      console.error('Error: --rank must be 1, 2, or 3');
      process.exit(2);
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const outputDir = options.out || path.join('.oss-preflight', 'runs', timestamp);
    const absoluteOutputDir = path.resolve(outputDir);

    console.log('\nOSS Preflight Run\n');
    console.log(`Idea: ${options.idea}`);
    console.log(`Output: ${absoluteOutputDir}\n`);

    const workflow: WorkflowTrace = createWorkflowTrace('idea', {
      idea: options.idea,
    });

    console.log('Step 1/4: Getting recommendations...');
    const { recommendations, brief, discovery } = await runRecommendPipeline(options.idea, {
      ...options,
      save: true,
    });

    if (recommendations.length === 0) {
      console.error('Error: No recommendations found');
      process.exit(1);
    }

    const searchMethod =
      discovery.method === 'search'
        ? 'registry-search'
        : discovery.method === 'search-with-catalog-fallback'
          ? 'search-with-catalog-fallback'
          : 'catalog-fallback';

    workflow.discoveryPlan = {
      ecosystem: brief.ecosystem,
      domain: brief.domain,
      searchQuery: brief.capabilities.join(', '),
      searchMethod,
    };

    const discoveredAt = new Date().toISOString();
    workflow.candidates = discovery.candidates.map((c) => ({
      name: c.name,
      source: c.source,
      discoveredAt,
    }));
    workflow.recommendations = recommendations;

    console.log(`Found ${recommendations.length} recommendations`);

    if (requestedRank !== null && requestedRank > recommendations.length) {
      console.error(`Error: Rank ${requestedRank} is out of bounds. Available recommendations: ${recommendations.length}`);
      process.exit(2);
    }

    const selectedRecommendation =
      requestedRank !== null
        ? recommendations[requestedRank - 1]
        : recommendations.find((rec) => rec.scaffoldAvailable && rec.templateId) ?? recommendations[0];

    if (!selectedRecommendation) {
      console.error(`Error: Could not find recommendation${requestedRank !== null ? ` at rank ${requestedRank}` : ''}`);
      process.exit(2);
    }

    console.log(
      `\nStep 2/4: Selected rank ${selectedRecommendation.rank}: ${selectedRecommendation.candidate.name}@${selectedRecommendation.candidate.version}\n`
    );

    if (!selectedRecommendation.scaffoldAvailable || !selectedRecommendation.templateId) {
      console.log('Step 3/4: No scaffold template is available; generating adoption pack...');
      fs.mkdirSync(absoluteOutputDir, { recursive: true });

      const adoptionPackPath = path.join(absoluteOutputDir, 'ADOPTION_PACK.md');
      fs.writeFileSync(adoptionPackPath, generateAdoptionPack(options.idea, selectedRecommendation), 'utf-8');

      workflow.actions.push({
        type: 'adoption-pack',
        timestamp: new Date().toISOString(),
        outputPath: adoptionPackPath,
        success: true,
      });
      workflow.generatedArtifacts.push(adoptionPackPath);
      workflow.verification.smokeTestPassed = null;

      const { workflowPath, reportPath } = writeWorkflowAndReport(
        absoluteOutputDir,
        workflow,
        options.idea,
        selectedRecommendation,
        null,
        null,
        adoptionPackPath,
        'adoption-pack'
      );

      console.log('Step 4/4: Verification skipped because no code was generated.');
      console.log(`Adoption pack: ${adoptionPackPath}`);
      console.log(`Workflow trace: ${workflowPath}`);
      console.log(`Summary report: ${reportPath}\n`);
      process.exit(0);
    }

    console.log('Step 3/4: Generating scaffold...');
    const scaffoldPath = path.join(absoluteOutputDir, 'scaffold');
    const scaffoldResult = await generateScaffold(selectedRecommendation, scaffoldPath);

    if (!scaffoldResult.success) {
      console.error(`Error: ${scaffoldResult.message}`);
      workflow.actions.push({
        type: 'scaffold',
        timestamp: new Date().toISOString(),
        outputPath: scaffoldPath,
        success: false,
      });
      process.exit(1);
    }

    console.log(`Scaffold generated at ${scaffoldPath}`);
    workflow.actions.push({
      type: 'scaffold',
      timestamp: new Date().toISOString(),
      outputPath: scaffoldPath,
      success: true,
    });
    workflow.generatedArtifacts.push(scaffoldPath);

    console.log('\nStep 4/4: Running smoke test...');
    const smokeResult = await runSmokeTest(scaffoldPath);

    await generateScaffold(selectedRecommendation, scaffoldPath, smokeResult);

    workflow.verification.smokeTestPassed = smokeResult.pass;
    if (!smokeResult.pass) {
      workflow.verification.validationErrors.push(smokeResult.output);
    }

    console.log(smokeResult.pass ? 'Smoke test PASSED' : 'Smoke test FAILED');
    console.log(`Duration: ${smokeResult.duration}ms\n`);

    const { workflowPath, reportPath } = writeWorkflowAndReport(
      absoluteOutputDir,
      workflow,
      options.idea,
      selectedRecommendation,
      smokeResult.pass,
      smokeResult.duration,
      scaffoldPath,
      'scaffold'
    );

    console.log('Generated artifacts:');
    console.log(`   - ${scaffoldPath}/`);
    console.log(`   - ${workflowPath}`);
    console.log(`   - ${reportPath}\n`);

    process.exit(smokeResult.pass ? 0 : 1);
  } catch (error) {
    console.error('Error:', error instanceof Error ? error.message : error);
    process.exit(2);
  }
}

// Made with Bob
