/**
 * Run Command - P9 Phase 2
 * 
 * Complete workflow: recommend, scaffold, verify, report
 * Orchestrates the full idea-to-scaffold pipeline
 */

import { runRecommendPipeline, type RecommendPipelineOptions } from './recommend-command.js';
import { generateScaffold, runSmokeTest } from '@oss-preflight/scaffold';
import { createWorkflowTrace, type WorkflowTrace } from '@oss-preflight/core';
import type { Recommendation } from '@oss-preflight/core';
import * as fs from 'fs';
import * as path from 'path';

export interface RunOptions extends RecommendPipelineOptions {
  idea: string;
  out?: string;
  rank?: string;
}

/**
 * Generate a summary report in markdown format
 */
function generateReport(
  idea: string,
  recommendation: Recommendation,
  smokeTestPassed: boolean,
  smokeDuration: number,
  scaffoldPath: string
): string {
  const report = `# OSS Preflight Run Report

## Input
**Idea:** ${idea}

## Selected Recommendation
**Package:** ${recommendation.candidate.name}@${recommendation.candidate.version}  
**Rank:** ${recommendation.rank}  
**Score:** ${recommendation.score.toFixed(2)}

### Evidence Passport
- **License:** ${recommendation.passport.facts.license?.value || 'Not available'}
- **Weekly Downloads:** ${recommendation.passport.facts.weeklyDownloads?.value || 'Not available'}
- **Stars:** ${recommendation.passport.facts.stars?.value || 'Not available'}
- **OpenSSF Score:** ${recommendation.passport.facts.openssfScore?.value || 'Not available'}

### Assessment
**Goal Fit:** ${recommendation.passport.interpretation.goalFit}

**Compatibility:** ${recommendation.passport.interpretation.compatibility}

${recommendation.passport.interpretation.tradeoffs.length > 0 ? `**Tradeoffs:**
${recommendation.passport.interpretation.tradeoffs.map(t => `- ${t}`).join('\n')}` : ''}

${recommendation.passport.interpretation.warnings.length > 0 ? `**Warnings:**
${recommendation.passport.interpretation.warnings.map(w => `- ⚠️ ${w}`).join('\n')}` : ''}

## Scaffold
**Output Path:** ${scaffoldPath}  
**Template:** ${recommendation.templateId || 'default'}

## Smoke Test
**Status:** ${smokeTestPassed ? '✅ PASSED' : '❌ FAILED'}  
**Duration:** ${smokeDuration}ms

## Next Steps
${smokeTestPassed ? `
1. Review the generated code in \`${scaffoldPath}\`
2. Install dependencies: \`cd ${scaffoldPath} && npm install\`
3. Review ADOPTION_REPORT.md for integration guidance
4. Customize the code for your specific use case
` : `
1. Review the smoke test errors
2. Check the generated code in \`${scaffoldPath}\`
3. Verify dependencies are correctly specified
4. Report issues if the scaffold template needs fixes
`}

---
*Generated by OSS Preflight*
`;

  return report;
}

/**
 * Run command handler - complete workflow
 */
export async function runCommand(options: RunOptions): Promise<void> {
  try {
    // Validate input
    if (!options.idea || options.idea.trim().length === 0) {
      console.error('Error: --idea is required');
      console.error('Usage: oss-preflight run --idea <string> [--out <directory>] [--rank <number>]');
      process.exit(2);
    }

    // Parse rank (1-indexed, default 1)
    const rank = options.rank ? parseInt(options.rank, 10) : 1;
    if (isNaN(rank) || rank < 1 || rank > 3) {
      console.error('Error: --rank must be 1, 2, or 3');
      process.exit(2);
    }

    // Determine output directory
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    const outputDir = options.out || path.join('.oss-preflight', 'runs', timestamp);
    const absoluteOutputDir = path.resolve(outputDir);

    console.log(`\n🚀 OSS Preflight Run\n`);
    console.log(`Idea: ${options.idea}`);
    console.log(`Output: ${absoluteOutputDir}\n`);

    // Create workflow trace
    const workflow: WorkflowTrace = createWorkflowTrace('idea', {
      idea: options.idea,
    });

    // Step 1: Run recommend with save
    console.log('📋 Step 1/4: Getting recommendations...');
    const { recommendations, brief, discovery } = await runRecommendPipeline(options.idea, {
      ...options,
      save: true,
    });

    if (recommendations.length === 0) {
      console.error('Error: No recommendations found');
      process.exit(1);
    }

    // Update workflow trace with the discovery method that was actually used
    // (live registry search vs. catalog fallback) — never an assumed value.
    const searchMethod =
      discovery.method === 'search'
        ? 'registry-search'
        : discovery.method === 'search-with-catalog-fallback'
          ? 'search-with-catalog-fallback'
          : 'catalog-fallback';

    workflow.discoveryPlan = {
      ecosystem: brief.ecosystem,
      domain: brief.domain,
      searchQuery: brief.capabilities.join(', '),
      searchMethod,
    };
    const discoveredAt = new Date().toISOString();
    workflow.candidates = discovery.candidates.map((c) => ({
      name: c.name,
      source: c.source,
      discoveredAt,
    }));
    workflow.recommendations = recommendations;

    // Step 2: Select recommendation by rank
    console.log(`✓ Found ${recommendations.length} recommendations`);
    
    if (rank > recommendations.length) {
      console.error(`Error: Rank ${rank} is out of bounds. Available recommendations: ${recommendations.length}`);
      process.exit(2);
    }

    const selectedRecommendation = recommendations[rank - 1];
    if (!selectedRecommendation) {
      console.error(`Error: Could not find recommendation at rank ${rank}`);
      process.exit(2);
    }
    console.log(`\n📦 Step 2/4: Selected rank ${rank}: ${selectedRecommendation.candidate.name}@${selectedRecommendation.candidate.version}\n`);

    // Step 3: Run scaffold
    console.log('🏗️  Step 3/4: Generating scaffold...');
    const scaffoldPath = path.join(absoluteOutputDir, 'scaffold');
    const scaffoldResult = await generateScaffold(selectedRecommendation, scaffoldPath);

    if (!scaffoldResult.success) {
      console.error(`Error: ${scaffoldResult.message}`);
      workflow.actions.push({
        type: 'scaffold',
        timestamp: new Date().toISOString(),
        outputPath: scaffoldPath,
        success: false,
      });
      process.exit(1);
    }

    console.log(`✓ Scaffold generated at ${scaffoldPath}`);
    workflow.actions.push({
      type: 'scaffold',
      timestamp: new Date().toISOString(),
      outputPath: scaffoldPath,
      success: true,
    });
    workflow.generatedArtifacts.push(scaffoldPath);

    // Step 4: Run smoke test
    console.log('\n🧪 Step 4/4: Running smoke test...');
    const smokeResult = await runSmokeTest(scaffoldPath);

    // Update adoption report with smoke test results
    await generateScaffold(selectedRecommendation, scaffoldPath, smokeResult);

    workflow.verification.smokeTestPassed = smokeResult.pass;
    if (!smokeResult.pass) {
      workflow.verification.validationErrors.push(smokeResult.output);
    }

    console.log(smokeResult.pass ? '✅ Smoke test PASSED' : '❌ Smoke test FAILED');
    console.log(`   Duration: ${smokeResult.duration}ms\n`);

    // Step 5: Write workflow trace
    const workflowPath = path.join(absoluteOutputDir, 'workflow.json');
    fs.mkdirSync(absoluteOutputDir, { recursive: true });
    fs.writeFileSync(workflowPath, JSON.stringify(workflow, null, 2), 'utf-8');
    console.log(`✓ Workflow trace: ${workflowPath}`);

    // Step 6: Write summary report
    const reportPath = path.join(absoluteOutputDir, 'REPORT.md');
    const report = generateReport(
      options.idea,
      selectedRecommendation,
      smokeResult.pass,
      smokeResult.duration,
      scaffoldPath
    );
    fs.writeFileSync(reportPath, report, 'utf-8');
    console.log(`✓ Summary report: ${reportPath}\n`);

    // Final summary
    console.log('📄 Generated artifacts:');
    console.log(`   - ${scaffoldPath}/`);
    console.log(`   - ${workflowPath}`);
    console.log(`   - ${reportPath}\n`);

    // Exit with appropriate code
    process.exit(smokeResult.pass ? 0 : 1);
  } catch (error) {
    console.error('Error:', error instanceof Error ? error.message : error);
    process.exit(2);
  }
}

// Made with Bob